### ISSUE TITLE
Title bar overflow

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/gratipay.com#4637]
![screen shot 2017-09-16 at 8 22 42 pm](https://user-images.githubusercontent.com/3893573/30513201-e05168c4-9b1c-11e7-8b99-b74664051b9d.png)

Looks like this happened after we added the 'Browse' tab.

**Comment by EdOverflow** [comment]
This could be resolved by increasing the `max-width` of the `#wrapper`.

```css
#wrapper {
    width: 98vw;
    max-width: 576px;
    margin: 0 auto;
}
```
