### ISSUE TITLE
Vertical Columns for Leaderboard

### ISSUE THREAD

**Issue by jeresig** [gratipay/gratipay.com#971]
A simple change which moves the horizontal rows of the leaderboard into vertical columns. This makes it so that you see more people, from each leaderboard, immediately upon viewing the page. Additionally it makes it easier to add a bunch more people, hooking in to #970.

![Screenshot](http://ejohn.org/files/screen/2013-05-20_1339.png)

CSS to make this happen:

``` css
#leaderboard {
  overflow: hidden;
  margin: 0 auto;
  width: 830px;
}

#leaderboard > * {
  width: 270px;
  float: left;
  margin-right: 10px;
}

#leaderboard > *:last-child {
  margin-right: 0;
}
```
